import type { Article, Topic, WordEntry } from "./types";
import { defaultLocale, getDict, type Locale } from "./i18n";

export const topics: Topic[] = [
  {
    id: "tech",
    title: { zh: "科技", en: "Technology" },
    description: {
      zh: "AI 正在如何重塑我们的工作与生活。",
      en: "How AI is reshaping the way we work and live.",
    },
    emoji: "💡",
    level: "Intermediate",
    articleId: "ai-rise",
  },
  {
    id: "travel",
    title: { zh: "旅行", en: "Travel" },
    description: {
      zh: "一位初到东京的旅行者的一天。",
      en: "A first-time visitor's day exploring Tokyo.",
    },
    emoji: "🗼",
    level: "Beginner",
    articleId: "tokyo-day",
  },
  {
    id: "health",
    title: { zh: "健康", en: "Health" },
    description: {
      zh: "每天散步——也许是最简单的健康习惯。",
      en: "Why a daily walk may be the simplest healthy habit.",
    },
    emoji: "🚶",
    level: "Beginner",
    articleId: "walking-benefits",
  },
  {
    id: "science",
    title: { zh: "科学", en: "Science" },
    description: {
      zh: "詹姆斯·韦伯太空望远镜揭示了什么。",
      en: "What the James Webb Space Telescope has revealed.",
    },
    emoji: "🔭",
    level: "Advanced",
    articleId: "webb-telescope",
  },
];

export const articles: Article[] = [
  {
    id: "ai-rise",
    topicId: "tech",
    title: "The Rise of Artificial Intelligence",
    subtitle: "How modern AI moved from research labs into daily life.",
    level: "Intermediate",
    minutes: 4,
    sentences: [
      {
        id: "s1",
        text: "Artificial intelligence has rapidly transformed many industries over the past decade.",
        translation: "在过去的十年里，人工智能迅速改变了许多行业。",
        grammar:
          "现在完成时 (has transformed) 强调动作从过去持续到现在。'over the past decade' 是表示时间段的状语。",
      },
      {
        id: "s2",
        text: "Modern systems can recognize images, translate languages, and generate human-like text.",
        translation: "现代系统能够识别图像、翻译语言并生成类似人类的文本。",
        grammar:
          "情态动词 'can' 表示能力；三个并列动词短语用逗号分隔，最后一个用 'and' 连接。",
      },
      {
        id: "s3",
        text: "Researchers train these models on enormous datasets collected from the internet.",
        translation: "研究人员在从互联网上收集的庞大数据集上训练这些模型。",
        grammar:
          "'collected from the internet' 是过去分词短语，作 'datasets' 的后置定语。",
      },
      {
        id: "s4",
        text: "Although the technology is powerful, it still makes mistakes that humans can easily spot.",
        translation: "尽管这项技术很强大，它仍然会犯一些人类轻易就能发现的错误。",
        grammar:
          "让步状语从句 'Although...'；'that humans can easily spot' 是修饰 'mistakes' 的定语从句。",
      },
      {
        id: "s5",
        text: "Many experts believe that thoughtful regulation will be essential in the years ahead.",
        translation: "许多专家认为，在未来几年里，深思熟虑的监管将是必不可少的。",
        grammar:
          "'that' 引导宾语从句作 'believe' 的宾语；'in the years ahead' 是时间状语。",
      },
    ],
  },
  {
    id: "tokyo-day",
    topicId: "travel",
    title: "A Day in Tokyo",
    subtitle: "Markets, temples, and neon lights in a single day.",
    level: "Beginner",
    minutes: 3,
    sentences: [
      {
        id: "s1",
        text: "Tokyo is a city where old traditions and modern technology live together.",
        translation: "东京是一座古老传统与现代科技共存的城市。",
        grammar:
          "'where' 引导定语从句修饰 'city'，表示地点。",
      },
      {
        id: "s2",
        text: "In the morning, I visited a quiet temple surrounded by tall buildings.",
        translation: "早上，我参观了一座被高楼包围的安静寺庙。",
        grammar:
          "'surrounded by tall buildings' 是过去分词短语，作 'temple' 的后置定语。",
      },
      {
        id: "s3",
        text: "For lunch I tried fresh sushi at a small restaurant near the fish market.",
        translation: "午餐我在鱼市场附近的一家小餐馆尝了新鲜的寿司。",
        grammar:
          "'near the fish market' 是介词短语，作 'restaurant' 的后置定语。",
      },
      {
        id: "s4",
        text: "At night, the streets of Shibuya were filled with bright neon signs.",
        translation: "夜晚，涩谷的街道上满是明亮的霓虹灯招牌。",
        grammar:
          "被动语态 'were filled with'，表示状态。",
      },
    ],
  },
  {
    id: "walking-benefits",
    topicId: "health",
    title: "The Benefits of a Daily Walk",
    subtitle: "A simple habit that improves both body and mind.",
    level: "Beginner",
    minutes: 3,
    sentences: [
      {
        id: "s1",
        text: "Walking is one of the simplest ways to stay healthy.",
        translation: "走路是保持健康最简单的方式之一。",
        grammar:
          "'one of the + 最高级 + 复数名词' 句型；不定式 'to stay healthy' 表目的。",
      },
      {
        id: "s2",
        text: "A short walk after meals can help your body digest food more easily.",
        translation: "饭后短暂散步可以帮助身体更轻松地消化食物。",
        grammar:
          "'help + sb. + do sth.' 结构；比较级 'more easily' 作状语。",
      },
      {
        id: "s3",
        text: "Doctors often recommend at least thirty minutes of walking every day.",
        translation: "医生通常建议每天至少走三十分钟。",
        grammar:
          "副词 'often' 修饰动词 'recommend'；'at least' 表示最低标准。",
      },
      {
        id: "s4",
        text: "Even a slow walk in the park can reduce stress and improve your mood.",
        translation: "即使是在公园里慢慢散步，也能减轻压力并改善心情。",
        grammar:
          "副词 'Even' 加强语气；并列动词 'reduce' 和 'improve' 共享主语 'a slow walk'。",
      },
    ],
  },
  {
    id: "webb-telescope",
    topicId: "science",
    title: "What Webb Has Shown Us",
    subtitle: "New views from the most powerful space telescope ever built.",
    level: "Advanced",
    minutes: 5,
    sentences: [
      {
        id: "s1",
        text: "The James Webb Space Telescope has been observing the universe since 2022.",
        translation: "詹姆斯·韦伯太空望远镜自 2022 年以来一直在观测宇宙。",
        grammar:
          "现在完成进行时 (has been observing) 强调动作从过去持续到现在并仍在进行。",
      },
      {
        id: "s2",
        text: "Unlike Hubble, Webb captures infrared light that older telescopes could not detect.",
        translation: "与哈勃望远镜不同，韦伯可以捕捉较旧望远镜无法探测到的红外光。",
        grammar:
          "'Unlike Hubble' 是介词短语作状语；'that older telescopes could not detect' 是定语从句修饰 'light'。",
      },
      {
        id: "s3",
        text: "Its images reveal galaxies whose light has traveled for billions of years.",
        translation: "它的图像展现了一些星系，那些星系的光已经传播了数十亿年。",
        grammar:
          "'whose' 引导定语从句，表所属关系，修饰 'galaxies'。",
      },
      {
        id: "s4",
        text: "Scientists hope these observations will help answer fundamental questions about cosmic origins.",
        translation: "科学家希望这些观测能够帮助回答关于宇宙起源的根本问题。",
        grammar:
          "'hope' 后省略 'that'，引导宾语从句；'help (to) answer' 中的不定式作宾语补足语。",
      },
    ],
  },
];

export const dictionary: Record<string, WordEntry> = {
  artificial: {
    word: "artificial",
    pronunciation: "/ˌɑːr.təˈfɪʃ.əl/",
    partOfSpeech: "adj.",
    definition: "Made by humans, especially as a copy of something natural.",
    translation: "人造的；人工的",
    example: "Artificial flowers can look surprisingly real.",
    exampleTranslation: "人造花看起来可以非常逼真。",
  },
  intelligence: {
    word: "intelligence",
    pronunciation: "/ɪnˈtel.ɪ.dʒəns/",
    partOfSpeech: "n.",
    definition: "The ability to learn, understand, and think about things.",
    translation: "智力；智能",
    example: "Her intelligence makes her a great problem solver.",
    exampleTranslation: "她的智慧让她成为一个出色的问题解决者。",
  },
  rapidly: {
    word: "rapidly",
    pronunciation: "/ˈræp.ɪd.li/",
    partOfSpeech: "adv.",
    definition: "Very quickly.",
    translation: "迅速地",
    example: "The city is changing rapidly.",
    exampleTranslation: "这座城市正在迅速变化。",
  },
  transformed: {
    word: "transformed",
    pronunciation: "/trænsˈfɔːrmd/",
    partOfSpeech: "v.",
    definition: "Past form of 'transform': to change something completely.",
    translation: "改变；转变",
    example: "The internet has transformed how we communicate.",
    exampleTranslation: "互联网改变了我们的交流方式。",
  },
  industries: {
    word: "industries",
    pronunciation: "/ˈɪn.də.striz/",
    partOfSpeech: "n.",
    definition: "Plural of 'industry': groups of companies producing similar goods or services.",
    translation: "行业；产业",
    example: "Many industries rely on skilled workers.",
    exampleTranslation: "许多行业依靠熟练的工人。",
  },
  decade: {
    word: "decade",
    pronunciation: "/ˈdek.eɪd/",
    partOfSpeech: "n.",
    definition: "A period of ten years.",
    translation: "十年",
    example: "The team has improved a lot in the last decade.",
    exampleTranslation: "在过去的十年里，这支队伍进步很大。",
  },
  recognize: {
    word: "recognize",
    pronunciation: "/ˈrek.əɡ.naɪz/",
    partOfSpeech: "v.",
    definition: "To know someone or something because you have seen or heard them before.",
    translation: "认出；识别",
    example: "I didn't recognize you with your new haircut.",
    exampleTranslation: "你换了新发型我都没认出你来。",
  },
  translate: {
    word: "translate",
    pronunciation: "/trænsˈleɪt/",
    partOfSpeech: "v.",
    definition: "To change words from one language into another.",
    translation: "翻译",
    example: "Could you translate this letter for me?",
    exampleTranslation: "你能帮我翻译这封信吗？",
  },
  generate: {
    word: "generate",
    pronunciation: "/ˈdʒen.ə.reɪt/",
    partOfSpeech: "v.",
    definition: "To produce or create something.",
    translation: "产生；生成",
    example: "Solar panels generate electricity from sunlight.",
    exampleTranslation: "太阳能电池板利用阳光发电。",
  },
  enormous: {
    word: "enormous",
    pronunciation: "/ɪˈnɔːr.məs/",
    partOfSpeech: "adj.",
    definition: "Extremely large in size or amount.",
    translation: "巨大的；庞大的",
    example: "They live in an enormous house by the lake.",
    exampleTranslation: "他们住在湖边一座巨大的房子里。",
  },
  datasets: {
    word: "datasets",
    pronunciation: "/ˈdeɪ.tə.sets/",
    partOfSpeech: "n.",
    definition: "Plural of 'dataset': a collection of related pieces of data.",
    translation: "数据集",
    example: "The model was trained on several public datasets.",
    exampleTranslation: "这个模型在多个公开数据集上训练。",
  },
  although: {
    word: "although",
    pronunciation: "/ɔːlˈðoʊ/",
    partOfSpeech: "conj.",
    definition: "Used to introduce a contrast: even though.",
    translation: "尽管；虽然",
    example: "Although it was raining, we went for a walk.",
    exampleTranslation: "尽管下着雨，我们还是去散步了。",
  },
  powerful: {
    word: "powerful",
    pronunciation: "/ˈpaʊ.ər.fəl/",
    partOfSpeech: "adj.",
    definition: "Having great strength or influence.",
    translation: "强大的；有力的",
    example: "This is a powerful argument.",
    exampleTranslation: "这是一个有力的论点。",
  },
  mistakes: {
    word: "mistakes",
    pronunciation: "/mɪˈsteɪks/",
    partOfSpeech: "n.",
    definition: "Plural of 'mistake': actions or judgments that are wrong.",
    translation: "错误",
    example: "Everyone makes mistakes sometimes.",
    exampleTranslation: "每个人都会犯错。",
  },
  spot: {
    word: "spot",
    pronunciation: "/spɒt/",
    partOfSpeech: "v.",
    definition: "To notice or recognize something.",
    translation: "发现；察觉",
    example: "Can you spot the difference between these two pictures?",
    exampleTranslation: "你能找出这两张图的不同吗？",
  },
  experts: {
    word: "experts",
    pronunciation: "/ˈek.spɜːrts/",
    partOfSpeech: "n.",
    definition: "People with a high level of skill or knowledge.",
    translation: "专家",
    example: "The experts disagree on the best approach.",
    exampleTranslation: "专家们对最佳方法意见不一。",
  },
  thoughtful: {
    word: "thoughtful",
    pronunciation: "/ˈθɔːt.fəl/",
    partOfSpeech: "adj.",
    definition: "Carefully considered; showing careful thought.",
    translation: "深思熟虑的",
    example: "She gave a thoughtful answer to the question.",
    exampleTranslation: "她对那个问题给出了深思熟虑的回答。",
  },
  regulation: {
    word: "regulation",
    pronunciation: "/ˌreɡ.jəˈleɪ.ʃən/",
    partOfSpeech: "n.",
    definition: "An official rule, or the act of controlling something.",
    translation: "监管；规定",
    example: "New regulation could affect the whole industry.",
    exampleTranslation: "新的监管规定可能影响整个行业。",
  },
  essential: {
    word: "essential",
    pronunciation: "/ɪˈsen.ʃəl/",
    partOfSpeech: "adj.",
    definition: "Absolutely necessary; extremely important.",
    translation: "必不可少的",
    example: "Water is essential for all living things.",
    exampleTranslation: "水对所有生物都是必不可少的。",
  },
  traditions: {
    word: "traditions",
    pronunciation: "/trəˈdɪʃ.ənz/",
    partOfSpeech: "n.",
    definition: "Customs or beliefs passed down through generations.",
    translation: "传统",
    example: "Many families have their own holiday traditions.",
    exampleTranslation: "许多家庭都有自己的节日传统。",
  },
  modern: {
    word: "modern",
    pronunciation: "/ˈmɒd.ən/",
    partOfSpeech: "adj.",
    definition: "Relating to the present or recent times.",
    translation: "现代的",
    example: "Modern phones can do almost anything.",
    exampleTranslation: "现代手机几乎能做任何事情。",
  },
  technology: {
    word: "technology",
    pronunciation: "/tekˈnɒl.ə.dʒi/",
    partOfSpeech: "n.",
    definition: "The use of scientific knowledge for practical purposes.",
    translation: "科技；技术",
    example: "Technology is changing how we learn.",
    exampleTranslation: "科技正在改变我们的学习方式。",
  },
  quiet: {
    word: "quiet",
    pronunciation: "/ˈkwaɪ.ət/",
    partOfSpeech: "adj.",
    definition: "Making little or no noise.",
    translation: "安静的",
    example: "The library is a quiet place to study.",
    exampleTranslation: "图书馆是一个安静的学习场所。",
  },
  temple: {
    word: "temple",
    pronunciation: "/ˈtem.pəl/",
    partOfSpeech: "n.",
    definition: "A building used for religious worship.",
    translation: "寺庙",
    example: "The temple is hundreds of years old.",
    exampleTranslation: "这座寺庙有几百年历史了。",
  },
  surrounded: {
    word: "surrounded",
    pronunciation: "/səˈraʊn.dɪd/",
    partOfSpeech: "v.",
    definition: "Past form of 'surround': to be all around something.",
    translation: "环绕；围绕",
    example: "The garden is surrounded by tall trees.",
    exampleTranslation: "花园被高大的树木环绕。",
  },
  fresh: {
    word: "fresh",
    pronunciation: "/freʃ/",
    partOfSpeech: "adj.",
    definition: "Recently made, picked, or prepared; not old.",
    translation: "新鲜的",
    example: "I love the smell of fresh bread.",
    exampleTranslation: "我喜欢新鲜面包的香味。",
  },
  market: {
    word: "market",
    pronunciation: "/ˈmɑːr.kɪt/",
    partOfSpeech: "n.",
    definition: "A place where people buy and sell goods.",
    translation: "市场",
    example: "I bought vegetables at the local market.",
    exampleTranslation: "我在本地市场买了蔬菜。",
  },
  bright: {
    word: "bright",
    pronunciation: "/braɪt/",
    partOfSpeech: "adj.",
    definition: "Full of light; shining strongly.",
    translation: "明亮的",
    example: "The room was bright and cheerful.",
    exampleTranslation: "房间明亮而欢快。",
  },
  neon: {
    word: "neon",
    pronunciation: "/ˈniː.ɒn/",
    partOfSpeech: "n.",
    definition: "A gas used in glowing lights and signs.",
    translation: "霓虹（灯）",
    example: "The bar had a pink neon sign in the window.",
    exampleTranslation: "酒吧的窗户上有一个粉色霓虹灯招牌。",
  },
  signs: {
    word: "signs",
    pronunciation: "/saɪnz/",
    partOfSpeech: "n.",
    definition: "Plural of 'sign': boards or notices that give information.",
    translation: "标志；招牌",
    example: "Follow the signs to the exit.",
    exampleTranslation: "按照指示牌走到出口。",
  },
  walking: {
    word: "walking",
    pronunciation: "/ˈwɔː.kɪŋ/",
    partOfSpeech: "n. / v.",
    definition: "The activity of moving on foot at a moderate pace.",
    translation: "步行；走路",
    example: "Walking is good exercise for almost everyone.",
    exampleTranslation: "走路对几乎每个人都是不错的运动。",
  },
  simplest: {
    word: "simplest",
    pronunciation: "/ˈsɪm.pləst/",
    partOfSpeech: "adj.",
    definition: "Superlative form of 'simple': the easiest or most basic.",
    translation: "最简单的",
    example: "The simplest answer is often the best.",
    exampleTranslation: "最简单的答案往往是最好的。",
  },
  healthy: {
    word: "healthy",
    pronunciation: "/ˈhel.θi/",
    partOfSpeech: "adj.",
    definition: "In good physical or mental condition.",
    translation: "健康的",
    example: "Eating vegetables helps you stay healthy.",
    exampleTranslation: "吃蔬菜有助于保持健康。",
  },
  digest: {
    word: "digest",
    pronunciation: "/daɪˈdʒest/",
    partOfSpeech: "v.",
    definition: "To break down food in your stomach so your body can use it.",
    translation: "消化",
    example: "It takes time to digest a heavy meal.",
    exampleTranslation: "消化一顿大餐需要时间。",
  },
  recommend: {
    word: "recommend",
    pronunciation: "/ˌrek.əˈmend/",
    partOfSpeech: "v.",
    definition: "To suggest that something is good or suitable.",
    translation: "推荐；建议",
    example: "I recommend this book to anyone learning English.",
    exampleTranslation: "我向所有学英语的人推荐这本书。",
  },
  reduce: {
    word: "reduce",
    pronunciation: "/rɪˈdjuːs/",
    partOfSpeech: "v.",
    definition: "To make something smaller or less.",
    translation: "减少",
    example: "Try to reduce the amount of sugar you eat.",
    exampleTranslation: "尽量减少糖的摄入量。",
  },
  stress: {
    word: "stress",
    pronunciation: "/stres/",
    partOfSpeech: "n.",
    definition: "Mental or emotional pressure or tension.",
    translation: "压力",
    example: "Exercise is a great way to handle stress.",
    exampleTranslation: "锻炼是缓解压力的好方法。",
  },
  improve: {
    word: "improve",
    pronunciation: "/ɪmˈpruːv/",
    partOfSpeech: "v.",
    definition: "To make or become better.",
    translation: "改善；提高",
    example: "Reading every day will improve your English.",
    exampleTranslation: "每天阅读会提高你的英语水平。",
  },
  mood: {
    word: "mood",
    pronunciation: "/muːd/",
    partOfSpeech: "n.",
    definition: "The way you are feeling at a particular time.",
    translation: "情绪；心情",
    example: "A good song can change my mood instantly.",
    exampleTranslation: "一首好歌能立刻改变我的心情。",
  },
  observing: {
    word: "observing",
    pronunciation: "/əbˈzɜːr.vɪŋ/",
    partOfSpeech: "v.",
    definition: "Watching something carefully in order to learn about it.",
    translation: "观察",
    example: "Scientists are observing the planet's climate.",
    exampleTranslation: "科学家正在观察这颗行星的气候。",
  },
  universe: {
    word: "universe",
    pronunciation: "/ˈjuː.nɪ.vɜːrs/",
    partOfSpeech: "n.",
    definition: "All of space and everything in it.",
    translation: "宇宙",
    example: "The universe is bigger than we can imagine.",
    exampleTranslation: "宇宙比我们想象的还要大。",
  },
  infrared: {
    word: "infrared",
    pronunciation: "/ˌɪn.frəˈred/",
    partOfSpeech: "adj.",
    definition: "Relating to light with a wavelength longer than visible red light.",
    translation: "红外线的",
    example: "The camera uses infrared light to see in the dark.",
    exampleTranslation: "这台相机使用红外光在黑暗中成像。",
  },
  detect: {
    word: "detect",
    pronunciation: "/dɪˈtekt/",
    partOfSpeech: "v.",
    definition: "To notice or discover something, often something hidden.",
    translation: "察觉；探测",
    example: "Sensors can detect even small movements.",
    exampleTranslation: "传感器能探测到极微小的动作。",
  },
  galaxies: {
    word: "galaxies",
    pronunciation: "/ˈɡæl.ək.siz/",
    partOfSpeech: "n.",
    definition: "Plural of 'galaxy': huge systems of stars, gas, and dust.",
    translation: "星系",
    example: "There are billions of galaxies in the universe.",
    exampleTranslation: "宇宙中有数十亿个星系。",
  },
  fundamental: {
    word: "fundamental",
    pronunciation: "/ˌfʌn.dəˈmen.təl/",
    partOfSpeech: "adj.",
    definition: "Forming a necessary base; very important.",
    translation: "根本的；基础的",
    example: "Practice is fundamental to learning a language.",
    exampleTranslation: "练习对学习语言至关重要。",
  },
  cosmic: {
    word: "cosmic",
    pronunciation: "/ˈkɒz.mɪk/",
    partOfSpeech: "adj.",
    definition: "Relating to the universe.",
    translation: "宇宙的",
    example: "Cosmic rays come from outer space.",
    exampleTranslation: "宇宙射线来自外太空。",
  },
  origins: {
    word: "origins",
    pronunciation: "/ˈɒr.ɪ.dʒɪnz/",
    partOfSpeech: "n.",
    definition: "Plural of 'origin': the beginning or source of something.",
    translation: "起源",
    example: "The origins of the language are unclear.",
    exampleTranslation: "这种语言的起源尚不清楚。",
  },
};

export function getArticle(id: string): Article | undefined {
  return articles.find((a) => a.id === id);
}

export function getTopic(id: string): Topic | undefined {
  return topics.find((t) => t.id === id);
}

export function lookupWord(raw: string, locale: Locale = defaultLocale): WordEntry {
  const key = raw.toLowerCase().replace(/[^a-z']/g, "");
  const found = dictionary[key];
  if (found) return found;
  const t = getDict(locale);
  return {
    word: raw,
    pronunciation: "—",
    partOfSpeech: "—",
    definition: t.panel.noEntry,
    translation: locale === "zh" ? "暂无释义" : "No translation yet",
    example: "—",
    exampleTranslation: "—",
  };
}
